/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smkyaop;
import database.Database;
import helper.Helper;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.Year;
import java.time.ZoneId;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JTable.AUTO_RESIZE_OFF;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bunga Permatasari
 */
public class PegawaiJabatForm extends javax.swing.JFrame {

    /**
     * Creates new form JabatanForm
     */
    public PegawaiJabatForm() {
        initComponents();
        loadData("");
        active(true);
    }
    


    private void loadData(String keys){
        String header[] = {"ID","ID Pegawai","Nama Pegawai","Tanggal Masuk","Tanggal Keluar","Masa Kerja"};
        DefaultTableModel dtm = new DefaultTableModel(null,header);
        table.setModel(dtm);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
          DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
                    table.getColumnModel().getColumn(0).setPreferredWidth(5); 
                    table.getColumnModel().getColumn(1).setPreferredWidth(5); 
          cellRenderer.setHorizontalAlignment(JLabel.CENTER);
          table.getColumnModel().getColumn(0).setCellRenderer(cellRenderer); 
          table.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);       
          
         String query = "SELECT pegawaijabat.*,pegawai.idpegawai as idp , pegawai.namapegawai as namap FROM pegawaijabat INNER JOIN pegawai ON pegawaijabat.idPegawai = pegawai.idpegawai"; 
          DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer();
          renderer.setHorizontalAlignment(0);                  
        String addQuery = "";
        if(keys != ""){
            addQuery = " WHERE p.namapegawai LIKE '%"+keys+"%' OR p.nip LIKE '%"+keys+"%' ";
        }
        try{            
            Connection conn = Database.getConn();
            PreparedStatement ps = conn.prepareStatement(query+addQuery);
            ResultSet rs = ps.executeQuery();            
            while(rs.next()){
                try{
                    SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy", new Locale("id","ID"));
                    java.util.Date date = new java.util.Date(rs.getDate(2).getTime());
                    String tgl = sdf.format(date);
                    java.util.Date date2 = null;
                    String tgl2 = "-";
                    if(rs.getDate(3) != null){
                        date2 = new java.util.Date(rs.getDate(4).getTime());
                        tgl2 = sdf.format(date2);                                    
                    }
                    Object[] row = {rs.getString(1),rs.getString(4),rs.getString(6),tgl,tgl2,rs.getString("masajabat") +" Tahun" };
                    dtm.addRow(row);                    
                }catch(Exception ex1){                    
                    ex1.printStackTrace();
                }

            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    
    private void clear(){
        tfId.setText("");
        tfId2.setText("");
        tfTglMasuk.setDate(null);
        tfTglKeluar.setDate(null);        
        tfCari.setText("Search By Nip or Name ");
    }
    
    private void firetable(){
        DefaultTableModel dtm = (DefaultTableModel)table.getModel();
        dtm.fireTableDataChanged();
    }
    
    private void active(boolean b){
        btnSave.setEnabled(b);
        btnDelete.setEnabled(!b);
        btnEdit.setEnabled(!b);
    }
    
    
    public void setFromPegawai(String id){
        tfId2.setText(id);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTglMasuk = new com.toedter.calendar.JDateChooser();
        tfTglKeluar = new com.toedter.calendar.JDateChooser();
        tfId2 = new javax.swing.JTextField();
        labelPegawai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pegawai Menjabat");

        jPanel1.setBackground(new java.awt.Color(25, 59, 104));

        jPanel2.setBackground(new java.awt.Color(20, 165, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 59, 104));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Menjabat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(20, 165, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 59, 104));
        jLabel2.setText("ID ");

        tfId.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfId.setEnabled(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 59, 104));
        jLabel3.setText("Tanggal Menjabat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 59, 104));
        jLabel4.setText("Pegawai");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 59, 104));
        jLabel5.setText("Tanggal Keluar");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("HAPUS");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("UBAH");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setText("BATAL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kembali.png"))); // NOI18N
        btnBack.setText("KEMBALI");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tfCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 59, 104));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caricari.png"))); // NOI18N

        tfTglMasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTglMasukFocusLost(evt);
            }
        });

        tfId2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfId2.setEnabled(false);

        labelPegawai.setBackground(new java.awt.Color(20, 165, 255));
        labelPegawai.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        labelPegawai.setForeground(new java.awt.Color(25, 59, 104));
        labelPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caricari.png"))); // NOI18N
        labelPegawai.setOpaque(true);
        labelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPegawaiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPegawaiMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPegawaiMouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Masukkan Nama / NIP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfId2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelPegawai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(88, 88, 88))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancel)
                        .addGap(44, 44, 44)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(80, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPegawai, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row >= 0 ){
            firetable();
        }
        
        
        
        String idpegawai = tfId2.getText();
        java.util.Date tglMasuk = tfTglMasuk.getDate();
        java.util.Date tglKeluar = tfTglKeluar.getDate();        
        String jenis = "";
        if(idpegawai.isEmpty()){
            Helper.alert("Isi Pegawai dulu!");
            return;
        }
        
        if(tglMasuk == null){
            Helper.alert("Isi Tanggal masuk  dulu");
            return;        
        }
        
        // menghitung berapa hari udah lewat dari ttgl a ke tanggal b       
        LocalDate local = tglMasuk.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate nowl = LocalDate.now();
        
        long year = java.time.temporal.ChronoUnit.DAYS.between(local, nowl);
        // hitung jumlah tanggal berdasarkan tahun kabisat atau tidak
        
        int hariTahunini = (Year.of(Year.now().getValue()).isLeap()) ? 366 : 365;
        
        long tahunJabat = year/hariTahunini;

        String query = "INSERT INTO pegawaijabat(mulai,keluar,idPegawai,masajabat) VALUES(?,?,?,?)";
        try{
            Connection conn = Database.getConn();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setDate(1, new java.sql.Date(tglMasuk.getTime()));
            if(tglKeluar == null){
                ps.setDate(2, null);
            }else{
                ps.setDate(2, new java.sql.Date(tglMasuk.getTime()));
            }
                ps.setInt(3, Integer.parseInt(idpegawai));
                ps.setInt(4, (int)tahunJabat);
                
            int result = ps.executeUpdate();
            if(result > 0 ){
                Helper.alert("Data Berhasil dimasukkan!");                
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        loadData("");
        clear();
        firetable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariActionPerformed
        // TODO add your handling code here:
        String keys = tfCari.getText();
        if(keys.isEmpty()){
            loadData("");
            return;
        }
        loadData(keys);
    }//GEN-LAST:event_tfCariActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row < 0){
            Helper.alert("PIlih data dahulu di tabel!");
            return;
        }
        String id = tfId.getText();
        
        int tanya = Helper.tanya("Apakah anda ingin menghapus data ini ?");
        if(tanya == JOptionPane.YES_OPTION && !id.isEmpty() ){
            try{
                PreparedStatement ps = Database.getConn().prepareStatement("DELETE fROM pegawaijabat WHERE id = ?");
                ps.setInt(1, Integer.parseInt(id));
                int hasil = ps.executeUpdate();
                if(hasil > 0 ){
                    Helper.alert("Data Berhasil dihapus!");
                }
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        loadData("");
        clear();
        firetable();
        active(true);        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        // menghitung berapa hari udah lewat dari ttgl a ke tanggal b
//        java.util.Date tgl = tfTglMasuk.getDate();
//        
//        LocalDate local = tgl.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//        LocalDate nowl = LocalDate.now();
//        
//        long year = java.time.temporal.ChronoUnit.DAYS.between(local, nowl);
//        System.out.println(year);

// mengecek apakah tahun kabisat
//        boolean isKabisat = Year.of(Year.now().getValue()).isLeap();

        clear();
        loadData("");
        firetable();
        active(true);        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        active(false);
        int row = table.getSelectedRow();
        String id = table.getValueAt(row, 0).toString();
        String idp = table.getValueAt(row, 1).toString();
        String namap = table.getValueAt(row, 2).toString();
        String tglMasuk = table.getValueAt(row, 3).toString();
        String tglKeluar = table.getValueAt(row, 4).toString();        
        tfId.setText(id);
        tfId2.setText(idp);
        java.util.Date tgl1 = null;
        java.util.Date tgl2 = null; 
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy", new Locale("id","ID"));        
        try{
            tgl1 = sdf.parse(tglMasuk);
            if(!tglKeluar.equals("-")){
                tgl2 = sdf.parse(tglKeluar);                        
            }
            tfTglMasuk.setDate(tgl1);
            tfTglKeluar.setDate(tgl2);
        }catch(ParseException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row < 0){
            Helper.alert("PIlih data dahulu di tabel!");
            return;
        }
        String id = tfId.getText();
        
        int tanya = Helper.tanya("Apakah anda ingin Mengupdate data ini ?");
        if(tanya == JOptionPane.YES_OPTION && !id.isEmpty() ){
            String idpegawai = tfId2.getText();
           
            java.util.Date tglMasuk = tfTglMasuk.getDate();
            java.util.Date tglKeluar = tfTglKeluar.getDate();        
            String jenis = "";
             if(id.isEmpty()){
                Helper.alert("Isi id dulu!");
                return;
            }
            if(idpegawai.isEmpty()){
                Helper.alert("Isi Pegawai dulu!");
                return;
            }

            if(tglMasuk == null){
                Helper.alert("Isi Tanggal masuk  dulu");
                return;        
            }
            
        LocalDate local = tglMasuk.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate nowl = LocalDate.now();
        
        long year = java.time.temporal.ChronoUnit.DAYS.between(local, nowl);
        // hitung jumlah tanggal berdasarkan tahun kabisat atau tidak
        int hariTahunini = (Year.of(Year.now().getValue()).isLeap()) ? 366 : 365;
        
        long tahunJabat = year/hariTahunini;            

            String query = "UPDATE pegawaijabat SET mulai = ?,keluar=?,idPegawai=?, masajabat = ? WHERE id = ?";
            try{
                Connection conn = Database.getConn();
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setDate(1, new java.sql.Date(tglMasuk.getTime()));
                if(tglKeluar == null){
                    ps.setDate(2, null);
                }else{
                    ps.setDate(2, new java.sql.Date(tglMasuk.getTime()));
                }
                
                ps.setInt(3, Integer.parseInt(idpegawai));
                ps.setInt(4,(int)tahunJabat);
                ps.setInt(5, Integer.parseInt(id));
                int result = ps.executeUpdate();
                if(result > 0 ){
                    Helper.alert("Data Berhasil dimasukkan!");                
                }
            }catch(SQLException ex){
                ex.printStackTrace();
            }

        }
        loadData("");
        clear();
        firetable();
        active(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void labelPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPegawaiMouseEntered
        // TODO add your handling code here:
        labelPegawai.setBackground(new Color(20, 121, 255));
        labelPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));        
        
    }//GEN-LAST:event_labelPegawaiMouseEntered

    private void labelPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPegawaiMouseExited
        // TODO add your handling code here:
                labelPegawai.setBackground(new Color(20,165,255));
            labelPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));                    
        
    }//GEN-LAST:event_labelPegawaiMouseExited

    private void labelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPegawaiMouseClicked
        // TODO add your handling code here:
        PegawaiForm.isFromPegawaiJabat = true;
        PegawaiForm.pj = this;
        PegawaiForm pj = new PegawaiForm();
        pj.setVisible(true);
    }//GEN-LAST:event_labelPegawaiMouseClicked

    private void tfTglMasukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTglMasukFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_tfTglMasukFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiJabatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiJabatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiJabatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiJabatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PegawaiJabatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPegawai;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfId2;
    private com.toedter.calendar.JDateChooser tfTglKeluar;
    private com.toedter.calendar.JDateChooser tfTglMasuk;
    // End of variables declaration//GEN-END:variables
}
