/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smkyaop;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import helper.Helper;
import java.sql.*;
import database.Database;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bunga Permatasari
 */
public class DataAbsenForm extends javax.swing.JFrame {

    /**
     * Creates new form DataAbsenForm
     */
    public DataAbsenForm() {
        initComponents();
        loadData("");
    }
    
    private void loadData(String keys){
      Object[] Baris ={"ID Absensi","ID Pegawai","Nama Pegawai", "Tanggal", "Jam Masuk","Jam Pulang","Status","Keterangan"};
      DefaultTableModel tabmode = new DefaultTableModel (null, Baris);
      table.setModel(tabmode);
      table.setRowHeight(40);
      String cari = "";
      String sql = "";
      if(keys != ""){
          cari = " WHERE pegawai.nip LIKE '%"+keys+"%' OR pegawainamapegawai LIKE '%"+keys+"%' ";
      }
      sql = "SELECT absensi.*,pegawai.namapegawai FROM absensi INNER JOIN pegawai ON absensi.idPegawai = pegawai.idpegawai";      
      try {
          java.sql.Connection conn = database.Database.getConn();
          java.sql.Statement stat = conn.createStatement();
          ResultSet hasil = stat.executeQuery(sql+cari);
          int index = 0;
          while(hasil.next()){
              SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy", new Locale("id","ID"));
                java.util.Date date = new java.util.Date(hasil.getDate(3).getTime());
                String tgl = sdf.format(date);
              String a = hasil.getString(1);
              String b = hasil.getString(2);
              String d = hasil.getString(4);
              String e = hasil.getString(5);
              String f = hasil.getString(6);
              String g = hasil.getString(7);
              String h = hasil.getString(8);

              Object[] data={a,b,h,tgl,d,e,f,g};
              tabmode.addRow(data);
          }
      }catch(SQLException e){   
          e.printStackTrace();
      }
         
        
    }
    
    private void clear(){
        tfId.setText("");
        tfId2.setText("");
        tfMasuk.setText("");
        tfPulang.setText("");
        combo.setSelectedIndex(0);
        tfTanggal.setDate(null);
    }
    
    private void firetable(){
        DefaultTableModel dtm = (DefaultTableModel)table.getModel();
        dtm.fireTableDataChanged();
    }
    
    private void active(boolean b){
        btnSave.setEnabled(b);
        btnDelete.setEnabled(!b);
        btnEdit.setEnabled(!b);
    }    
    
    public void setFromPegawai(String id){
        tfId2.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tfTanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfId2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfMasuk = new javax.swing.JTextField();
        tfPulang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfId1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 59, 104));

        jPanel2.setBackground(new java.awt.Color(20, 165, 255));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 59, 104));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Absensi Pegawai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(20, 165, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("HAPUS");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("UBAH");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancel.setText("BATAL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kembali.png"))); // NOI18N
        btnBack.setText("KEMBALI");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 59, 104));
        jLabel2.setText("ID");

        tfId.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfId.setEnabled(false);

        tfId2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfId2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 59, 104));
        jLabel3.setText("ID Pegawai");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 59, 104));
        jLabel4.setText("Tanggal");

        tfMasuk.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMasukActionPerformed(evt);
            }
        });

        tfPulang.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 59, 104));
        jLabel5.setText("Masuk");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 59, 104));
        jLabel6.setText("Pulang");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 59, 104));
        jLabel7.setText("-");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- silahkan Pilih Keterangan ---", "Masuk", "Alfa", "Izin" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 59, 104));
        jLabel8.setText("Keterangan");

        tfId1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tfId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfId1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 59, 104));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caricari.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(20, 165, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 59, 104));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caricari.png"))); // NOI18N
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Masukkan Nama / NIP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(61, 61, 61)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCancel)
                .addGap(44, 44, 44)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 267, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfId, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfId2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(tfMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(89, 89, 89)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(tfPulang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfId1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfId1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfId2)
                        .addComponent(tfId, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfMasuk)
                        .addComponent(tfPulang)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();

        String idp = tfId2.getText();
        String masuk = tfMasuk.getText();
        String pulang = tfPulang.getText();
        java.util.Date tgl = tfTanggal.getDate();
        String keterangan = "";
        int index = combo.getSelectedIndex();
        if(idp.isEmpty()){
            Helper.alert("Isi pegawai dulu!");
            return;
        }
        
        if(tgl == null){
            Helper.alert("Masukkan tanggal!");
            return;
        }

        if(index == 0){
            Helper.alert("Pilih Keterangan dahulu!");
            return;
        }
        java.util.Date masuktime = null,pulangtime=null;
        if(!masuk.isEmpty()){
            try {
                 masuktime = new SimpleDateFormat("HH:mm").parse(masuk);              
            } catch (ParseException ex) {
               Helper.alert("masukkan jam masuk dengan benar!");
               return;
            }
        }
        
        if(!pulang.isEmpty()){
            try {
                 pulangtime = new SimpleDateFormat("HH:mm").parse(pulang);                 
            } catch (ParseException ex) {
               Helper.alert("masukkan jam pulang dengan benar!");
               return;
            }
        }
            
        keterangan = combo.getSelectedItem().toString();
        
        if(keterangan.contains("--")){
            Helper.alert("Pilih Keterangan dulu!");
               return;
        }
        
        String query = "INSERT INTO absensi(idpegawai,tanggal,jamMasuk,jamPulang,status,keterangan) VALUES(?,?,?,?,?,?)";
        try{
            Connection conn = Database.getConn();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, Integer.parseInt(idp));
            ps.setDate(2, new java.sql.Date(tgl.getTime()));
            ps.setTime(3,new java.sql.Time(masuktime.getTime()));
            ps.setTime(4,new java.sql.Time(pulangtime.getTime()));            
            ps.setInt(5,index);
            ps.setString(6, keterangan);
            int result = ps.executeUpdate();
            if(result > 0 ){
                Helper.alert("Data Berhasil dimasukkan!");
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        loadData("");
        clear();
        firetable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row < 0){
            Helper.alert("PIlih data dahulu di tabel!");
            return;
        }
        String id = tfId.getText();

        int tanya = Helper.tanya("Apakah anda ingin menghapus data ini ?");
        if(tanya == JOptionPane.YES_OPTION && !id.isEmpty() ){
            try{
                PreparedStatement ps = Database.getConn().prepareStatement("DELETE fROM absensi WHERE idAbsensi = ?");
                ps.setInt(1, Integer.parseInt(id));
                int hasil = ps.executeUpdate();
                if(hasil > 0 ){
                    Helper.alert("Data Berhasil dihapus!");
                }
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        loadData("");
        clear();
        firetable();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row < 0){
            Helper.alert("PIlih data dahulu di tabel!");
            return;
        }
        String id = tfId.getText();

        int tanya = Helper.tanya("Apakah anda ingin Mengupdate data ini ?");
        if(tanya == JOptionPane.YES_OPTION && !id.isEmpty() ){

            String idp = tfId2.getText();
            String masuk = tfMasuk.getText();
            String pulang = tfPulang.getText();
            java.util.Date tgl = tfTanggal.getDate();
            String keterangan = "";
            int index = combo.getSelectedIndex();
            keterangan = combo.getSelectedItem().toString();
            if(idp.isEmpty()){
                Helper.alert("Isi pegawai dulu!");
                return;
            }

            if(tgl == null){
                Helper.alert("Masukkan tanggal!");
                return;
            } 

            if(index == 0){
                Helper.alert("Pilih Keterangan dahulu!");
                return;
            }
            java.util.Date masuktime = null,pulangtime=null;
            if(!masuk.isEmpty()){
                try {
                     masuktime = new SimpleDateFormat("HH:mm").parse(masuk);              
                } catch (ParseException ex) {
                   Helper.alert("masukkan jam masuk dengan benar!");
                   return;
                }
            }

            if(!pulang.isEmpty()){
                try {
                     pulangtime = new SimpleDateFormat("HH:mm").parse(pulang);                 
                } catch (ParseException ex) {
                   Helper.alert("masukkan jam pulang dengan benar!");
                   return;
                }
            }


            String query = "UPDATE absensi SET idpegawai = ?,tanggal=?,jamMasuk=?,jamPulang=?,status=?,keterangan=? WHERE idAbsensi = ?";
            try{
                Connection conn = Database.getConn();
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setInt(1, Integer.parseInt(idp));
                ps.setDate(2, new java.sql.Date(tgl.getTime()));
                ps.setTime(3,new java.sql.Time(masuktime.getTime()));
                ps.setTime(4,new java.sql.Time(pulangtime.getTime()));            
                ps.setInt(5,index);
                ps.setString(6, keterangan);
                ps.setInt(7,Integer.parseInt(id));
                int result = ps.executeUpdate();
                if(result > 0 ){
                    Helper.alert("Data Berhasil diUpdate!");
                }
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        loadData("");
        clear();
        firetable();

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clear();
        loadData("");
        firetable();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMasukActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
//      Object[] Baris ={"ID Absensi","ID Pegawai","Nama Pegawai", "Tanggal", "Jam Masuk","Jam Pulang","Status","Keterangan"};
        int row = table.getSelectedRow();
        String id = table.getValueAt(row,0).toString();
        String idp = table.getValueAt(row,1).toString();
        String tanggal = table.getValueAt(row,3).toString();
        String jammasuk = table.getValueAt(row,4).toString();
        String jampulang = table.getValueAt(row,5).toString();
        String status = table.getValueAt(row,6).toString();
        String keterangan = table.getValueAt(row,7).toString();    
        
        try{
            tfId.setText(id);
            tfId2.setText(idp);
            tfMasuk.setText(jammasuk);
            tfPulang.setText(jampulang);
            combo.setSelectedIndex(Integer.parseInt(status));
            java.util.Date tgl = new SimpleDateFormat("dd MMMM yyyy", new Locale("id","ID")).parse(tanggal);
            tfTanggal.setDate(tgl);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        PegawaiForm.isFromDataAbsen = true;
        PegawaiForm.absen = this;
        PegawaiForm form = new PegawaiForm();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
            jLabel10.setBackground(new Color(20,165,255));
            jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));            
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setBackground(new Color(20, 121, 255));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));          
    }//GEN-LAST:event_jLabel10MouseEntered

    private void tfId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfId1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAbsenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAbsenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAbsenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAbsenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataAbsenForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfId1;
    private javax.swing.JTextField tfId2;
    private javax.swing.JTextField tfMasuk;
    private javax.swing.JTextField tfPulang;
    private com.toedter.calendar.JDateChooser tfTanggal;
    // End of variables declaration//GEN-END:variables
}
