/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smkyaop;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bunga Permatasari
 */
public class HelperTable extends javax.swing.JFrame {

    /**
     * Creates new form HelperTable
     */
    public static boolean isFromGajiNon = false;
    public static PenggajianNon gajinon = null;    
    public static boolean isFromGajiTen = false;
    public static PenggajianTendik gajiT = null;    
    public static PiketTendik piket = null;
    public static BpjsPegawai bpjs = null;
    public HelperTable() {
        initComponents();
        loadData("");
    }
    
    private int tunjabat = 0;
    
   private void loadData(String keys) {
      Object[] Baris ={"ID Pegawai","Nama Pegawai","NIP", "Jabatan","gty","walas","Tunjangan Jabatan","Gaji Pokok"};
      DefaultTableModel tabmode = new DefaultTableModel (null, Baris);
      table.setModel(tabmode);
      table.setRowHeight(40);
      String flag = "";
      
      if(isFromGajiTen) flag = "'Tendik'";
      if(isFromGajiNon) flag = "'Non-Tendik'";
      if(piket!= null) flag += " 'Tendik' AND p.gty = 1 ";
      String cari =" WHERE j.jenisjabatan = "+flag;
      if(keys != ""){
          cari += " AND (pegawai.nip LIKE '%"+keys+"%' OR pegawai.namapegawai LIKE '%"+keys+"%') ";
      }
        String sql = "SELECT p.idpegawai,p.namapegawai,p.nip,j.namajabatan,j.jenisjabatan,p.gty,p.walas,j.tunjanganJabatan as tj,j.gapok FROM pegawai AS P INNER JOIN jabatan AS j ON  "
              + "p.idjabatan = j.idjabatan";
        
        if(bpjs!= null){
            sql = "SELECT p.idpegawai,p.namapegawai,p.nip,j.namajabatan,j.jenisjabatan, bp.idpegawai,p.gty,p.walas,j.tunjanganJabatan as tj,j.gapok FROM pegawai as p "
                    + "INNER JOIN jabatan as j ON p.idjabatan = j.idjabatan LEFT JOIN bpjspegawai as bp ON p.idpegawai = bp.idpegawai WHERE bp.idbpjspegawai IS NULL; ";
            if(keys != "") cari = " AND p.nip LIKE '%"+keys+"%' OR p.namapegawai LIKE '%"+keys+"%'";
            else cari = "";

        }
        
       System.out.println(sql+cari);
       //return;
          DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer();
          renderer.setHorizontalAlignment(0);          
                  table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
          table.getColumnModel().getColumn(0).setPreferredWidth(10);       
          DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
          cellRenderer.setHorizontalAlignment(JLabel.CENTER);
          table.getColumnModel().getColumn(0).setCellRenderer(cellRenderer); 
          table.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);  
          table.getColumnModel().getColumn(2).setCellRenderer(cellRenderer); 
          table.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);         
      
      try {
          java.sql.Connection conn = database.Database.getConn();
          java.sql.Statement stat = conn.createStatement();
          ResultSet hasil = stat.executeQuery(sql+cari);
          int index = 0;
          while(hasil.next()){
              String a = hasil.getString(1);
              String b = hasil.getString(2);
              String c = hasil.getString(3);
              String d = hasil.getString(4) +","+hasil.getString(5);
              Object[] data={a,b,c,d,hasil.getBoolean("gty"),hasil.getBoolean("walas"),hasil.getString("tj"),
              hasil.getString("gapok")};
              tabmode.addRow(data);
          }
      }catch(SQLException e){   
          e.printStackTrace();
      }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(25, 59, 104));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Masukkan Nama / NIP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row < 0) {
            dispose();
            return;
        }
        String idpegawai = table.getValueAt(row,0).toString();
        boolean gty = Boolean.parseBoolean(table.getValueAt(row,4).toString() ) ;        
        boolean walas =  Boolean.parseBoolean(table.getValueAt(row,5).toString() ) ;
        String tj = table.getValueAt(row,6).toString();
        String gapok = table.getValueAt(row,7).toString();
        if(isFromGajiNon){
                gajinon.setFromPegawai(idpegawai,gty,walas,Integer.parseInt(tj),Integer.parseInt(gapok));
                isFromGajiNon = false;
                gajinon = null;
                dispose();
            }
            if(isFromGajiTen){
                gajiT.setFromPegawai(idpegawai,gty,walas,Integer.parseInt(tj));
                  isFromGajiTen = false;
                  gajiT = null;  
                dispose();
            }        
            
            if(piket != null){
                piket.setFromPiket(idpegawai);
                piket = null;
                dispose();
            }
            
            if(bpjs != null){
                bpjs.setFromPiket(idpegawai);
                bpjs = null;
                dispose();
            }
            
    }//GEN-LAST:event_tableMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String keys = jTextField1.getText();
        if(keys.isEmpty()){
            loadData("");
        }else{
            loadData(keys);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelperTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelperTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelperTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelperTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelperTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
